SET SERVEROUTPUT ON
 DECLARE
 AREA NUMBER(7,3);
  PI CONSTANT NUMBER := 3.14;
  RADIUS NUMBER(7);
  BEGIN
  RADIUS := &RADIUS;
  AREA := PI*POWER(RADIUS, 2);
  DBMS_OUTPUT.PUT_LINE('RADIUS = ' || RADIUS);
  DBMS_OUTPUT.PUT_LINE('AREA = '||AREA);
  END;
 /
